export const ADD_IN_FAVORITE_IN_START = 'ADD_IN_FAVORITE_IN_START';
export const ADD_IN_FAVORITE_IN_SUCCESS = 'ADD_IN_FAVORITE__IN_SUCCESS';
export const ADD_IN_FAVORITE_IN_FAIL = 'ADD_IN_FAVORITE__IN_FAIL';