export const GET_FILTERED_PRODUCTS_IN_START = 'GET_FILTERED_PRODUCTS_IN_START';
export const GET_FILTERED_PRODUCTS_IN_SUCCESS = 'GET_FILTERED_PRODUCTS_IN_SUCCESS';
export const GET_FILTERED_PRODUCTS_IN_FAIL = 'GET_FILTERED_PRODUCTS_IN_FAIL';